### PR TITLE
Restructure OGM website

### PR DESCRIPTION
**Pull request by rmseifried**
This PR restructures the OGM website according to our design doc, as described in this issue: https://github.com/geoblacklight/geoblacklight-metadata/issues/28

Note that I'm not done migrating content from the wiki so *this issue is not yet resolved*, but I wanted to get this restructuring into `main` so that any future changes to the Aardvark documentation can be integrated without running into directory location issues. 

___
List of changes in each commit:

**Initial restructuring**
* change note margin from 40px to 0px
* delete .DS_Store doc
* create `legacy-schemas` and migrate GBL 1.0 content from wiki
* create skeleton structure for `about-our-schemas` and start migrating content from wiki

**initial feedback + continued migration**
* renamed "current schemas" to "current schema"
* renamed "legacy schemas" to "legacy versions"
* finished migrating "about-our-schema" content and moved some into "helpful resources" to keep it simple
* updating code examples to Aardvark examples where necessary

**complete new structure for site**
* copied most recent "About Aardvark" to `index.md` under `current-schema`
* copied most recent Aardvark schema docs into `current-schema` and updated headers to new directory structure
* finished creating empty pages for "Helpful Resources"

### CODE REVIEW

**Comment by karenmajewicz** [comment]
I am working on the file conflicts locally. Otherwise, I think this is a great foundation and am inclined to merge it. Any feedback @kgjenkins ?

**Comment by rmseifried** [comment]
@karenmajewicz I don't understand the code on the "changed files" for the commit you just made, but one file (geometry.md) looks like it got reverted to its former headings. It should read: 

```
parent: OGM Aardvark
grand_parent: Current Schema
```

**Comment by karenmajewicz** [comment]
That one got skipped in the error message for some reason. GitHub is insisting on adding unnecessary and conflicting info in the headers that I am trying to remove. I will try to get the geometry one to work.

**Comment by karenmajewicz** [comment]
I noticed a duplicate order number for Resource Type and fixed it. Then, I changed the table row to be called "Order". Does that seem OK?

**Comment by rmseifried** [comment]
> I noticed a duplicate order number for Resource Type and fixed it. 

Nice catch! 

> Then, I changed the table row to be called "Order". Does that seem OK?

Seems OK to me! We can always change it if need be in the future.

**Review by karenmajewicz — APPROVED** [review]

**Pull request merged**
