### PR TITLE
big reorg

### PR DESCRIPTION
**Pull request by karenmajewicz**
As I tried to divide the site into the concept of "repositories" and "metadata", this is the structure I came up with. It is still a draft and could be refined, but what do you think about this direction?

### CODE REVIEW

**Comment by karenmajewicz** [comment]
Screen Shot 2022-07-07 at 2 48 05 PM
Screen Shot 2022-07-07 at 2 48 12 PM

**Comment by rmseifried** [comment]
I think there are some good ideas in here. I'd suggest taking a step back and hashing out an outline (as a group perhaps) before making the changes in the code and doing a pull request. We have an open issue about this (https://github.com/OpenGeoMetadata/opengeometadata.github.io/issues/36) with a Google Doc where we were brainstorming the site re-organization. Could we sketch out ideas there first?

**Review by rmseifried — CHANGES_REQUESTED** [review]
See comments in conversation

**Comment by karenmajewicz** [comment]
> I think there are some good ideas in here. I'd suggest taking a step back and hashing out an outline (as a group perhaps) before making the changes in the code and doing a pull request. We have an open issue about this (#36) with a Google Doc where we were brainstorming the site re-organization. Could we sketch out ideas there first?

Yes, I think that's a good idea. With this branch, I was mainly working through the idea that we have two different purposes going on at the public site (how to add to repos and the metadata schema). I didn't really consider that confusing until I had not looked at the site for awhile. Then, it stuck out to me as confusing.

**Comment by karenmajewicz** [comment]
Could we revisit this idea this week?

**Comment by rmseifried** [comment]
@karenmajewicz @kgjenkins - I spun up a draft outline in the [Google Doc](https://docs.google.com/document/d/19xYyNxMWbf6ZE5kw5qKe0vfX_lZ21GnZSEcacbDXcJM/edit). Below my outline, Keith and I made some notes about other things we'd like to change during this reorganization. Thoughts?

**Pull request closed without merging**
